name: unit-test
on: pull_request
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database:
        - sqlite3
        - postgres
    env:
      KOKO_TEST_DB: ${{ matrix.database }}
    steps:
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-unit-${{ hashFiles('**/go.sum') }}
    - name: setup-db
      if: ${{ matrix.database == 'postgres'}}
      run: |
        ./scripts/setup-db.sh &
        ./scripts/wait-for-db.sh
    - name: Cache go-atc-router library
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/lib/libatc_router*
        key: ${{ runner.os }}-go-atc-router-${{ hashFiles('**/go.sum') }}
    - name: make test-race
      run: make test-race

